import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    width: '100%',
  },
  main: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    position: 'absolute',
    top: 144,
    left: 65,
  },
  name: {
    fontSize: 24,
    color: '#0026AB',
    fontWeight: 'bold',
    marginTop: 20,
  },
  detail: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    color: '#5163A4',
  },
  bottom: {
    marginHorizontal: 30,
    position: 'absolute',
    bottom: 58,
  },
  emailButton: {
    height: 48,
    backgroundColor: '#3E5CFA',
  },
  emailText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '400',
  },
  emailDetail: {
    marginTop: 10,
    textAlign: 'center',
    color: '#6D7175',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  lineBackground: {
    backgroundColor: '#E4E9F0',
    height: 1,
  },
  lineLeft: {
    backgroundColor: '#ffffff',
    width: 50,
    marginTop: -8,
    marginHorizontal: 135,
  },
  orText: {
    color: '#6D7175',
    fontSize: 12,
    textAlign: 'center',
  },
  googleAndFacebook: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  google: {
    width: 44,
    height: 44,
  },
  facebook: {
    width: 44,
    height: 44,
  },
  // container: {
  //   paddingLeft: 16,
  //   paddingRight: 16,
  //   marginTop: 150,
  //   flex: 1,
  //   alignItems: 'center',
  //   backgroundColor: '#ffffff',
  //   // position: 'relative',
  // },
  // main: {
  //   display: 'flex',
  //   flex: 1,
  //   backgroundColor: '#ffffff',
  //   // ,
  // },
  // user: {
  //   display: 'flex',
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   height: 34,
  // },
  // userName: {
  //   fontSize: 24,
  //   fontStyle: 'normal',
  //   fontWeight: '700',
  //   background: 'linear-gradient(133.04deg, #7A2EF6 11.45%, #F62EE2 146.07%)',
  //   backgroundClip: 'text',
  // },
  // userTag: {
  //   display: 'flex',
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   marginLeft: 8,
  //   paddingTop: 4,
  //   paddingBottom: 4,
  //   paddingLeft: 8,
  //   paddingRight: 8,
  //   borderRadius: 8,
  //   border: '1px solid #EDEDED',
  //   boxSizing: 'border-box',
  // },
  // userTagText: {
  //   marginLeft: 2,
  // },
  // tagList: {
  //   marginTop: 16,
  //   display: 'flex',
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   flexWrap: 'wrap',
  //   gap: 6,
  // },
  // tagListItem: {
  //   display: 'flex',
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   height: 28,
  //   paddingTop: 4,
  //   paddingBottom: 4,
  //   paddingLeft: 10,
  //   paddingRight: 10,
  //   borderRadius: 6,
  //   flexShrink: 1,
  // },
  // tagListItemTip: {
  //   width: 10,
  //   height: 10,
  //   borderRadius: 100,
  //   marginRight: 6,
  // },
  // tagListItemText: {
  //   fontWeight: '500',
  //   fontSize: 12,
  //   lineHeight: 14,
  //   color: '#3A0D84',
  // },
  // actions: {
  //   width: '100%',
  //   display: 'flex',
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'space-between',
  //   marginTop: 32,
  // },
  // actionsItem: {
  //   display: 'flex',
  //   flexDirection: 'column',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   width: 161.5,
  //   height: 88,
  //   backgroundColor: '#F6F6F6',
  //   borderRadius: 12,
  // },
  // actionsItemText: {
  //   marginTop: 6,
  //   lineHeight: 22,
  //   color: '#7A2EF6',
  //   fontSize: 14,
  //   fontWeight: '700',
  //   fontStyle: 'normal',
  // },
  // description: {
  //   marginTop: 20,
  //   padding: 12,
  //   boxSizing: 'border-box',
  //   backgroundColor: '#F6F6F6',
  //   borderRadius: 12,
  // },
  // descriptionTitle: {
  //   lineHeight: 22,
  //   fontWeight: '700',
  //   fontSize: 14,
  //   marginBottom: 5,
  //   color: '#1F1F1F',
  // },
  // descriptionValue: {
  //   lineHeight: 22,
  //   fontSize: 14,
  //   fontWeight: '400',
  //   fontStyle: 'normal',
  //   color: '#1F1F1F',
  // },
  // action: {
  //   position: 'absolute',
  //   left: 0,
  //   bottom: 0,
  //   height: 72,
  //   width: 375,
  //   boxSizing: 'border-box',
  //   display: 'flex',
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
  // actionMain: {
  //   width: 343,
  //   marginLeft: 16,
  //   display: 'flex',
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   borderRadius: 12,
  //   backgroundColor: '#7A2EF6',
  //   height: 48,
  // },
  // actionChat: {
  //   color: '#FFFFFF',
  //   fontSize: 14,
  //   fontStyle: 'normal',
  //   fontWeight: '700',
  // },
})

export { styles }
