import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    paddingTop: 32,
    paddingBottom: 32,
    paddingLeft: 16,
    paddingRight: 16,
    flex: 1,
    backgroundColor: '#ffffff',
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
    position: 'relative',
  },
  main: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  user: {
    marginTop: 5,
    height: 34,
  },
  userName: {
    fontSize: 24,
    lineHeight: 34,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  userTag: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: 8,
    border: '1px solid #EDEDED',
    boxSizing: 'border-box',
  },
  userTagText: {
    marginLeft: 2,
  },
  tagList: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },

  actions: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  actionsItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: 4,
    height: 88,
    backgroundColor: '#F6F6F6',
    borderRadius: 12,
  },
  actionsItemText: {
    marginTop: 6,
    lineHeight: 22,
    color: '#7A2EF6',
    fontSize: 14,
    fontWeight: '700',
    fontStyle: 'normal',
  },
  description: {
    marginTop: 16,
    width: '100%',
    paddingHorizontal: 12,
    marginBottom: 40,
    backgroundColor: '#F6F6F6',
    borderRadius: 12,
  },
  descriptionTitle: {
    lineHeight: 28,
    fontWeight: '700',
    fontSize: 14,
    color: '#1F1F1F',
  },
  descriptionValue: {
    fontSize: 14,
    fontWeight: '400',
    fontStyle: 'normal',
    color: '#1F1F1F',
  },
  actionMain: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#7A2EF6',
    height: 48,
  },
  actionChat: {
    color: '#FFFFFF',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '700',
  },
})

export { styles }
